# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTMxwW2mMHn7QUohuYRIJ_vqp8SxO87G
"""

from tkinter import *
import requests
import json

root=Tk()
root.title("App del tiempo")
root.geometry("600x400")

# creamos la funcion del boton
def botonn():

  # url de la api
  """ 
  https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=89129&distance=5&API_KEY=A03B04A1-C109-4585-BAFA-666EC203CB04
  """

  # esta es la informacion que nos devuelve la url
  # como podemos ver es una lista con 3 elementos los cuales cada uno es un diccionario
  # el primer elemento es el 03, el segundo el PM2.5 y el tercero el PM10
  """
  [{"DateObserved":"2022-05-05 ","HourObserved":0,"LocalTimeZone":"PST","ReportingArea":"Las Vegas","StateCode":"NV","Latitude":36.206,"Longitude":-115.223,"ParameterName":"O3","AQI":35,"Category":{"Number":1,"Name":"Good"}},
  {"DateObserved":"2022-05-05 ","HourObserved":0,"LocalTimeZone":"PST","ReportingArea":"Las Vegas","StateCode":"NV","Latitude":36.206,"Longitude":-115.223,"ParameterName":"PM2.5","AQI":48,"Category":{"Number":1,"Name":"Good"}},
  {"DateObserved":"2022-05-05 ","HourObserved":0,"LocalTimeZone":"PST","ReportingArea":"Las Vegas","StateCode":"NV","Latitude":36.206,"Longitude":-115.223,"ParameterName":"PM10","AQI":34,"Category":{"Number":1,"Name":"Good"}}]

  """

  # hacemos una excepcion por si no funcionase
  try:
    # creamos la conexion con el metodo requests.get() y la url 
    api_requests=requests.get("https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=" + cp.get() + "&distance=5&API_KEY=A03B04A1-C109-4585-BAFA-666EC203CB04")
    # cargamos con el metodo json.loads()
    api=json.loads(api_requests.content)
    # guardamos en las variables lo contenido en el elemento 1 de la lista que nos interesa
    ciudad=api[0]["ReportingArea"]
    calidad=api[0]["AQI"]
    categoria=api[0]["Category"]["Name"]

    # le damos color al label segun el nombre de la categoria (tambien se podria con el numero de la categoria)
    if categoria=="Good":
      color="green"
    elif categoria=="Moderate":
      color="yellow"
    elif categoria=="Unhealthy for Sensitive Groups":
      color="orange"
    elif categoria=="Unhealthy":
      color="red"
    elif categoria=="Very Unhealthy":
      color="purple"
    elif categoria=="Hazardous":
      color="maroon"

    root.config(bg=color)

    # creamos un label 
    myLabel=Label(root, text="ciudad" + ciudad + "Calidad aire" + str(calidad) + "Categoria" + categoria, font=("Helvetica",20))
    myLabel.pack()

    # borramos el contenido del entry
    cp.delete(0,END)
    
  except Exception as e:
    api="Error..."


cp=Entry(root)
cp.grid(row=1, column=0)

boton=Button(root, text="introduce el cp", command=botonn)
boton.grid(row=1, column=1)

root.mainloop()